// Accept only opaque IDs generated by the browser, never free-form identity.
export function normalizeMetricSessionId(value: unknown): string {
  if (typeof value !== "string") return "";
  return /^(?:[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}|session-[a-z0-9]{1,16}-[a-z0-9]{1,24})$/i.test(value)
    ? value
    : "";
}
